### ISSUE TITLE
[iOS] Incorrect button colors

### ISSUE THREAD

**Issue by michaeltintiuc** [ModusCreateOrg/beep#104]
**Describe the bug**
The check button on account and password pages should be red, it is blue. Same goes for the close (x) and Done buttons on all modals.

**To Reproduce**
1. Go to either Account or Password check pages or open any modal
2. Observe the incorrect color of the above mentioned buttons

**Expected behavior**
The buttons should be of a reddish color, same as the other UI elements

**Screenshots or videos**
![screenshot from 2018-09-21 17 31 44](https://user-images.githubusercontent.com/1321256/45888327-7215b680-bdc6-11e8-96f8-9b1501c346cc.png)
![screenshot from 2018-09-21 17 42 36](https://user-images.githubusercontent.com/1321256/45888328-72ae4d00-bdc6-11e8-8700-c2bb55201e5f.png)

**Comment by ElNinjaGaiden** [comment]
This is addressed on https://github.com/ModusCreateOrg/beep/pull/127
