### ISSUE TITLE
npm run build-android

### ISSUE THREAD

**Issue by philipnjuguna66** [ModusCreateOrg/beep#117]
i have an error in

npm run build-android
npm ERR! missing script: build-android

npm ERR! A complete log of this run can be found in:
npm ERR!     /

this is log 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-android' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose stack Error: missing script: build-android
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:280:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd /var/www/html/test
6 verbose Linux 4.15.0-34-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build-android"
8 verbose node v8.12.0
9 verbose npm  v6.4.1
10 error missing script: build-android
11 verbose exit [ 1, true ]

**Comment by michaeltintiuc** [comment]
@philipnjuguna66 The only thing that stands out is this:
`verbose stack Error: missing script: build-android`

Try running the commands found in packge.json:

`"build-android": "npx cap sync android && npx cap copy android",`

**Comment by michaeltintiuc** [comment]
You would do that with Android Studio, will close this issue as it does not relate to Beep
