### ISSUE TITLE
Image missing from Beep app

### ISSUE THREAD

**Issue by peterennis** [ModusCreateOrg/beep#121]
**Describe the bug**

Image missing from Beep

**To Reproduce**
1. Install app on Android device from Play Store
2. Enter email
3. See results
4. This problem also exists on the list of hacked vendors

**Expected behavior**

Some picture/icon
![beep](https://user-images.githubusercontent.com/140737/49916128-4a2a7200-fe4e-11e8-9abb-549a22623a4c.jpg)

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: LG K20 V
 - OS: Android 7.0

**Additional context**

**Comment by michaeltintiuc** [comment]
This was fixed in #120 and will be released soon.
