### ISSUE TITLE
Beep modal links

### ISSUE THREAD

**Issue by alin-baicoci** [ModusCreateOrg/beep#129]
Add links where necessary on Beep's modal description:

“Vue.JS and Ionic Framework” wording should link to Ionic Vue library. The link is https://github.com/ionic-team/ionic/pull/15801
- “Vue.JS and Ionic Framework” wording should be underline(see "How does it work?" link) 
- Link should have a “Modus red” (#ff5c5d) hover state

“Beep” should link to Beep’s landing page. The link is https://labs.moduscreate.com/beep-vue-ionic-hybrid-mobile-app 
- “Beep” wording should be underline(see "How does it work?" link)  
- Link should have a “Modus red” (#ff5c5d) hover state
- “Beep” word appears 3 times on the modal.

**Comment by ecris87** [comment]
For this issue, the styling / class created in the PR for #128 should be reused.

**Comment by ecris87** [comment]
Thanks for the PR @GTITI , you rock!
