### ISSUE TITLE
Large screen - How it works

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/beep#71]
**Describe the bug**
How it works is in the same line with the main buttons when on large screens

**To Reproduce**
1. Go to https://beep.modus.app
2. Observe in landscape mode (width > height)

**Expected behavior**
_How it works_ is at the bottom

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/733074/45024683-de0fc500-b039-11e8-9c51-225c45c11745.png)

**Comment by michaeltintiuc** [comment]
Fixed by #87
