### ISSUE TITLE
iOS - password font doesn't match the style

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/beep#72]
**Describe the bug**
The font in password <input> doesn't match other font styles

**To Reproduce**
1. Launch the app on iOS
2. Type in a password

**Expected behavior**
Same as other fonts

**Screenshots or videos**
### Password field
![image](https://user-images.githubusercontent.com/733074/45024859-3e066b80-b03a-11e8-89bc-16ac5ad84444.png)

### Username field (looks ok)
![image](https://user-images.githubusercontent.com/733074/45024862-3fd02f00-b03a-11e8-92fc-5dc13b5c4600.png)

**Comment by michaeltintiuc** [comment]
Fixed by #88
