### ISSUE TITLE
App is not closed when user hits Android device native back button

### ISSUE THREAD

**Issue by skolovrat-modus** [ModusCreateOrg/beep#83]
**Is your feature request related to a problem? Please describe.**
App is not closed when a user hits Android native back button

Actual result: 
 - App is not closed. Nothing happens on hit on Android back button
- Only choice is to hide the app to run in background

Expected result:
- App is closed when user hits Android back button  

**Describe the solution you'd like**
App is closed when user hits Android native back button

**Comment by grgur** [comment]
Fixed in #92. Thanks for reporting!
