### ISSUE TITLE
Buttons in the top corners are hard to press on iPhone X

### ISSUE THREAD

**Issue by mtrajkovska-modus** [ModusCreateOrg/beep#86]
**Describe the bug**
On iPhone X the buttons in the top right and left corners are very hard to press. 

**To Reproduce**
1. Start the app
2. Go to Account - Back button is difficult to tap
3. Type in any account - Check button is difficult to tap
- Same on Check Password screen

**Expected behavior**
The buttons should be lower so that they don't interfere with the iPhone status bar. Same should be applied for the page titles.

**Screenshots or videos**
http://prntscr.com/kudztg

**Smartphone (please complete the following information):**
 - Device: [iPhone X]
 - OS: [iOS 12]

**Comment by michaeltintiuc** [comment]
This could either be an upstream issue with the safezone CSS rule or the custom themeing, @belov91 could you take a peek?
