### ISSUE TITLE
Typo in "How does it work?" page

### ISSUE THREAD

**Issue by mikelafortune** [ModusCreateOrg/beep#91]
In the 'Pioneering Vue...' paragraph, there is an extra space between 'have to struggle with' and 'Angular'.

**To Reproduce**
1. Open app
2. Click on 'How does it work?'
3. Scroll down to 'Pioneering Vue' paragraph body copy
4. See typo as above

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 11.2.1

**Comment by michaeltintiuc** [comment]
Thanks @mikelafortune, looks like it was the dangling `&nbsp;` causing the error, no idea why they were there in the first place :man_shrugging:

**Comment by grgur** [comment]
Fixed in #93 
Thanks for reporting!
