### ISSUE TITLE
[Feature] Ask for review

### ISSUE THREAD

**Issue by grgur** [ModusCreateOrg/beep#94]
It would be nice to ask users for a review in the app store.

We could use a Cordova plugin such as https://github.com/pushandplay/cordova-plugin-apprate

Capacitor might work OOB with that plugin https://capacitor.ionicframework.com/docs/basics/cordova/

## Workflow idea
* User checks for username/pass
* Beep show results (red or green)
* User navigates away
* Beep prompts for review

**Comment by michaeltintiuc** [comment]
I think that workflow is perfect :+1:

**Comment by grgur** [comment]
@ElNinjaGaiden owns this now :)

**Comment by grgur** [comment]
@ElNinjaGaiden completed this in #103
