### ISSUE TITLE
Back button is not responding on "How does it work?" screen

### ISSUE THREAD

**Issue by namrata-modus** [ModusCreateOrg/beep#99]
Back button is not responding on "How does it work?" screen like it happens on "Hash Protected"

1.  Open App on Android Device
2. Click on "Account" icon
3. Click on "how does it work?"
4. You will be on description screen
5. Use Back button from device device 
**Expected behavior**
It should redirects to previous screen like it happens on "Hash Protected"

**Comment by michaeltintiuc** [comment]
This is already resolved in the master branch, but requires a new version from Capacitor
